# Generated by Django 6.0 on 2025-12-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_teacher', models.CharField(max_length=100)),
                ('course_duration', models.IntegerField()),
                ('seat_number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Course',
            },
        ),
    ]
